Se habilita SSL en el transcendence
RobertoRobrodri/ft_transcendence pull request #19
Opened 2024-03-19 20:59 UTC by jalvarad-1

Se crean por ahora los certificados SSL para utilizarlos en django y en nginx.
Se modifica la configuración de red para que los servicios únicamente sean accesibles por https en el puerto 443 de nginx, asegurando un único método de entrada a cualquier parte de nuestro proyecto desde la red externa.

2024-03-19 21:01 UTC, jalvarad-1 commented on back/core/core/asgi.py
> +from game.routing import websocket_game
este orden es necesario con daphne, ya que si no devuelve un error por cargar el base user antes de la app

2024-03-20 08:11 UTC, RobertoRobrodri commented on back/core/pong_auth/views.py
> -            'redirect_uri': "http://localhost:80",
Solo recordar que debemos actualizar la aplicación en la intra para cambiar la url

2024-03-20 08:13 UTC, RobertoRobrodri commented on front/html/login/login.html
> +                    onclick="location.href='https://api.intra.42.fr/oauth/authorize?client_id=u-s4t2ud-fabc70636434a6e13642cb70d96dd9b25d6d0d1416e676828df55c45808e06bc&redirect_uri=https%3A%2F%2Floca
Lo mismo, aquí la aplicación de la intra generará una nueva url, nada que rompa solo tenerlo en cuenta

2024-03-20 08:19 UTC, RobertoRobrodri commented on compose.yml
> -      - 8000:8000
Restaura estas líneas, necesitamos esto para acceder a la zona de admin y al swagger

2024-03-20 08:20 UTC, RobertoRobrodri requested changes
De mi parte todo genial. Una vez esté mergeado actualizaré la aplicación de la intra con la nueva redirect uri.

Por otro lado, en el compose necesitamos exponer los puertos 8000 de django para nosotros acceder a la zona de admin y al swagger. Al menos por ahora en dev es una herramienta útil

2024-03-20 08:42 UTC, jalvarad-1 commented on compose.yml
> -      - 8000:8000
a todo eso le puedo crear un location, y el puerto no tiene porque estar expuesto, la gracia es que todo se accede desde nginx, y si llegamos a poner WAF, será global para todo, en caso de dejar ese puerto abierto el WAF no aplicaría, y perdería un poco el sentido

2024-03-20 08:43 UTC, jalvarad-1 commented on compose.yml
> -      - 8000:8000
el swagger es util? no tengo muy claro para que sirve

2024-03-20 08:46 UTC, jalvarad-1 commented on compose.yml
> -      - 8000:8000
además que si añadimos dominio, no podriamos hacer domain/admin, cosa que configurando todo via nginx sí se podría

2024-03-20 09:10 UTC, jalvarad-1 commented on compose.yml
> -      - 8000:8000
vale, lo he modificado y dejado abierto ese puerto

2024-03-20 09:20 UTC, RobertoRobrodri approved these changes

2024-03-20 10:34 UTC, merged